In [3]:
pip install yfinance --upgrade --no-cache-dir

Collecting yfinance
  Downloading yfinance-0.1.63.tar.gz (26 kB)
Requirement already satisfied, skipping upgrade: pandas>=0.24 in c:\users\isaac\anaconda3\lib\site-packages (from yfinance) (1.1.3)
Requirement already satisfied, skipping upgrade: numpy>=1.15 in c:\users\isaac\anaconda3\lib\site-packages (from yfinance) (1.19.2)
Requirement already satisfied, skipping upgrade: requests>=2.20 in c:\users\isaac\anaconda3\lib\site-packages (from yfinance) (2.24.0)
Collecting multitasking>=0.0.7
  Downloading multitasking-0.0.9.tar.gz (8.1 kB)
Requirement already satisfied, skipping upgrade: lxml>=4.5.1 in c:\users\isaac\anaconda3\lib\site-packages (from yfinance) (4.6.1)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.7.3 in c:\users\isaac\anaconda3\lib\site-packages (from pandas>=0.24->yfinance) (2.8.1)
Requirement already satisfied, skipping upgrade: pytz>=2017.2 in c:\users\isaac\anaconda3\lib\site-packages (from pandas>=0.24->yfinance) (2020.1)
Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in c:\users\isaac\anaconda3\lib\site-packages (from requests>=2.20->yfinance) (2.10)
Requirement already satisfied, skipping upgrade: chardet<4,>=3.0.2 in c:\users\isaac\anaconda3\lib\site-packages (from requests>=2.20->yfinance) (3.0.4)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\isaac\anaconda3\lib\site-packages (from requests>=2.20->yfinance) (1.25.11)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in c:\users\isaac\anaconda3\lib\site-packages (from requests>=2.20->yfinance) (2020.6.20)
Requirement already satisfied, skipping upgrade: six>=1.5 in c:\users\isaac\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas>=0.24->yfinance) (1.15.0)
Building wheels for collected packages: yfinance, multitasking
  Building wheel for yfinance (setup.py): started
  Building wheel for yfinance (setup.py): finished with status 'done'
  Created wheel for yfinance: filename=yfinance-0.1.63-py2.py3-none-any.whl size=23914 sha256=9c60e8f8ac8024f2adbde16c37ae7a2bacfd9bbd7b276959a69a13a2fc44a9d0
  Stored in directory: C:\Users\Isaac\AppData\Local\Temp\pip-ephem-wheel-cache-xttf2y2j\wheels\ec\cc\c1\32da8ee853d742d5d7cbd11ee04421222eb354672020b57297
  Building wheel for multitasking (setup.py): started
  Building wheel for multitasking (setup.py): finished with status 'done'
  Created wheel for multitasking: filename=multitasking-0.0.9-py3-none-any.whl size=8372 sha256=59279c578efdc223c2b712e2bb07019db533b0bbd691c51fd798f80da2da54c4
  Stored in directory: C:\Users\Isaac\AppData\Local\Temp\pip-ephem-wheel-cache-xttf2y2j\wheels\57\6d\a3\a39b839cc75274d2acfb1c58bfead2f726c6577fe8c4723f13
Successfully built yfinance multitasking
Installing collected packages: multitasking, yfinance
Successfully installed multitasking-0.0.9 yfinance-0.1.63
Note: you may need to restart the kernel to use updated packages.

In [1]:
import yfinance as yf

In [2]:
tsla = yf.Ticker('TSLA')
# we could use a database to maintain a list of ticker symbols
# and loop through them like an array

In [3]:
# use "period" instead of start/end
# valid periods: 1d,5d,1mo,3mo,6mo,1y,2y,5y,10y,ytd,max
# (optional, default is '1mo')
tsla.history(period='5d')

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2021-08-17,672.659973,674.580017,648.840027,665.710022,23721300,0,0
2021-08-18,669.750000,695.770020,669.349976,688.989990,20349400,0,0
2021-08-19,678.210022,686.549988,667.590027,673.469971,14313500,0,0
2021-08-20,682.849976,692.130005,673.700012,680.260010,14781800,0,0
2021-08-23,685.442017,712.129883,680.750488,706.299988,20069007,0,0

In [4]:
# fetch data by interval (including intraday if period < 60 days)
# valid intervals: 1m,2m,5m,15m,30m,60m,90m,1h,1d,5d,1wk,1mo,3mo
# (optional, default is '1d')
tsla.history(period='5d', interval='60m')

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Datetime,,,,,,,
2021-08-17 09:30:00-04:00,672.659973,674.549988,661.229980,667.094177,6437572,0,0
2021-08-17 10:30:00-04:00,667.080994,670.842224,660.109985,660.109985,2918038,0,0
2021-08-17 11:30:00-04:00,660.109985,661.799988,655.210083,658.967285,2658037,0,0
2021-08-17 12:30:00-04:00,658.799622,659.469971,651.700012,655.380005,3253812,0,0
2021-08-17 13:30:00-04:00,655.380005,659.799988,648.840027,655.650024,2908715,0,0
2021-08-17 14:30:00-04:00,655.739990,662.729919,653.390015,661.518005,2414892,0,0
2021-08-17 15:30:00-04:00,661.629883,666.840027,660.529602,665.859985,1920622,0,0
2021-08-18 09:30:00-04:00,670.130005,688.669922,669.520020,687.683228,6386503,0,0
2021-08-18 10:30:00-04:00,687.640015,693.809875,687.182312,689.950012,3474252,0,0
2021-08-18 11:30:00-04:00,690.000000,693.219971,686.570007,691.237427,1924124,0,0
2021-08-18 12:30:00-04:00,691.250000,693.830017,688.240601,689.199219,1438797,0,0
2021-08-18 13:30:00-04:00,689.169983,693.199890,684.719971,691.005493,1763382,0,0
2021-08-18 14:30:00-04:00,691.121704,695.770020,690.739990,691.724976,2180096,0,0
2021-08-18 15:30:00-04:00,691.640015,692.849976,688.169983,689.289978,1838956,0,0
2021-08-19 09:30:00-04:00,678.210022,686.549988,673.000000,677.659973,4920901,0,0
2021-08-19 10:30:00-04:00,677.799988,680.489990,674.849976,677.956970,2022752,0,0
2021-08-19 11:30:00-04:00,678.030029,681.000000,676.500000,677.344727,1339122,0,0
2021-08-19 12:30:00-04:00,677.349976,680.059998,676.950012,678.219971,838019,0,0
2021-08-19 13:30:00-04:00,678.570007,678.570007,670.369995,670.679993,1384151,0,0
2021-08-19 14:30:00-04:00,670.630005,676.468384,667.590027,676.000000,1775293,0,0
2021-08-19 15:30:00-04:00,676.119995,677.270020,671.729980,673.469971,1220577,0,0
2021-08-20 09:30:00-04:00,682.849976,692.129883,676.900024,677.539917,5489472,0,0
2021-08-20 10:30:00-04:00,677.525024,679.234985,673.700012,676.169983,2106926,0,0
2021-08-20 11:30:00-04:00,676.164978,680.000000,674.380005,677.369995,1805590,0,0
2021-08-20 12:30:00-04:00,677.359985,678.510010,676.150024,677.500000,898412,0,0
2021-08-20 13:30:00-04:00,677.580017,679.080017,674.919983,678.079895,996060,0,0
2021-08-20 14:30:00-04:00,678.000122,681.549988,677.469971,679.739990,1395860,0,0
2021-08-20 15:30:00-04:00,679.729980,681.119995,679.684998,680.099976,1260847,0,0
2021-08-23 09:30:00-04:00,685.442017,704.708496,680.750488,702.750000,6427315,0,0
2021-08-23 10:30:00-04:00,702.659973,706.770020,701.039978,704.969971,3395207,0,0
2021-08-23 11:30:00-04:00,704.979980,710.859985,704.070007,707.729980,2952408,0,0
2021-08-23 12:30:00-04:00,707.700073,711.119995,707.250000,711.119995,1589170,0,0
2021-08-23 13:30:00-04:00,711.174988,712.129883,708.570007,709.399902,1582761,0,0
2021-08-23 14:30:00-04:00,709.409729,710.094421,704.770020,704.799988,1627099,0,0
2021-08-23 15:30:00-04:00,704.859985,707.580017,704.289978,706.179993,1568542,0,0